### ISSUE TITLE
Fix any pep8 error

### ISSUE THREAD

**Issue by luiscarlossf** [luiscarlossf/pdi_project#7]

**Comment by Flugschwein** [comment]
Will work on this.

**Comment by StegSchreck** [comment]
I added PR https://github.com/luiscarlossf/pdi_project/pull/12 for you to check.

**Comment by earthquakesan** [comment]
@StegSchreck imo simply fixing space is not enough, there should be tox setup for the project to have automatic pre-commit PEP8 check.

**Comment by StegSchreck** [comment]
@earthquakesan I did not only fix whitespaces, but also refactored some naming, as far as it was possible. Which is not easy when a repo is not in English. You should consider using English only in your source good. Using something else is just bad practice, as you exclude everyone else from helping you.

As I already wrote in my PR, a CI pipeline and a proper IDE would help you a lot to prevent these errors. But this was is part of this ticket.

**Comment by luiscarlossf** [comment]
@StegSchreck Thanks so much for your contribution. That project is to my graduate. You have reason.  Now, any parts aren't in English, but I want to translate soon.
